"use client";

import { useEffect, useMemo, useState } from "react";

const nav = [["dashboard", "Dashboard", "⌂"], ["transactions", "Transactions", "▤"], ["analytics", "Budget & Analytics", "◔"], ["insights", "AI Insights", "✦"], ["afford", "Can I Afford This?", "⌁"]];
const categories = ["Food & Dining", "Shopping", "Transport", "Entertainment", "Bills", "Health", "Other"];
const color = ["c0", "c1", "c2", "c3"];
const rupees = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const money = (value) => rupees.format(Number(value || 0));

async function api(path, options = {}) {
  const response = await fetch(`/api/proxy${path}`, { headers: { "Content-Type": "application/json", ...options.headers }, ...options });
  const text = await response.text(); let data = {};
  try { data = text ? JSON.parse(text) : {}; } catch { throw new Error("The server returned an invalid response."); }
  if (!response.ok) throw new Error(data.detail || "Request failed.");
  return data;
}
const Panel = ({ children, className = "" }) => <section className={`panel ${className}`}>{children}</section>;
const Empty = ({ children }) => <div className="empty">{children}</div>;
function Metric({ label, value, note, tone = "blue" }) { return <Panel className="metric"><div><span>{label}</span><i className={tone}>●</i></div><strong>{value}</strong><small>{note}</small></Panel>; }
function Heading({ title, subtitle, action }) { return <div className="heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }

export default function Home() {
  const [user, setUser] = useState(null), [checking, setChecking] = useState(true), [page, setPage] = useState("dashboard"), [expenses, setExpenses] = useState([]), [budget, setBudget] = useState(0), [error, setError] = useState("");
  const load = async () => { try { const [list, currentBudget] = await Promise.all([api("/expenses"), api("/budget")]); setExpenses(list); setBudget(currentBudget.monthly_amount); setError(""); } catch (e) { setError(e.message); } };
  useEffect(() => { api("/me").then(setUser).catch(() => setUser(null)).finally(() => setChecking(false)); }, []);
  useEffect(() => { if (user) load(); }, [user]);
  const total = useMemo(() => expenses.reduce((sum, item) => sum + Number(item.amount), 0), [expenses]);
  if (checking) return <main className="auth"><div>Loading FinSight…</div></main>;
  if (!user) return <Auth onLogin={setUser} />;
  return <main className="app"><aside><div className="brand"><b>◉</b><span>FinSight</span></div><nav>{nav.map(([id, label, icon]) => <button key={id} onClick={() => setPage(id)} className={page === id ? "active" : ""}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="profile"><b>{user.username[0].toUpperCase()}</b><div><strong>{user.username}</strong><small>Personal workspace</small></div><button onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); setUser(null); }}>↪</button></div></aside><section className="work"><header><div className="search">⌕ <input placeholder="Search expenses, insights..." /></div><button onClick={() => setPage("transactions")}>+ Add expense</button></header><div className="canvas">{error && <div className="notice error">{error}</div>}{page === "dashboard" && <Dashboard expenses={expenses} total={total} budget={budget} go={setPage} />}{page === "transactions" && <Transactions expenses={expenses} load={load} />}{page === "analytics" && <Analytics expenses={expenses} total={total} budget={budget} setBudget={setBudget} />}{page === "insights" && <Insights total={total} budget={budget} />}{page === "afford" && <Afford total={total} budget={budget} />}</div></section></main>;
}

function Dashboard({ expenses, total, budget, go }) {
  const remaining = budget - total; const grouped = groupExpenses(expenses);
  return <><Heading title="Overview" subtitle="A clear view of your spending and monthly budget." action={<button className="primary" onClick={() => go("transactions")}>+ Add expense</button>} /><div className="metrics"><Metric label="Monthly budget" value={money(budget)} note="Set this in Budget & Analytics" /><Metric label="Total spent" value={money(total)} note={`${expenses.length} tracked expenses`} tone="orange" /><Metric label="Remaining" value={money(remaining)} note={remaining >= 0 ? "Still available this month" : "You are over budget"} tone={remaining >= 0 ? "green" : "purple"} /><Metric label="Top category" value={grouped[0]?.category || "—"} note={grouped[0] ? money(grouped[0].total) : "No expenses yet"} tone="purple" /></div><div className="grid"><Panel><h2>Budget progress</h2><p>Your monthly spending against the budget.</p><div className="budget-ring"><b>{budget ? `${Math.min(100, Math.round(total / budget * 100))}%` : "—"}</b><span>used</span></div><div className="progress big"><i className="c0" style={{ width: `${budget ? Math.min(100, total / budget * 100) : 0}%` }} /></div><div className="progress-label"><span>{money(total)} spent</span><span>{money(Math.max(0, remaining))} remaining</span></div></Panel><Panel><h2>Spending by category</h2><p>Your biggest areas of spending.</p>{grouped.length ? grouped.slice(0, 4).map((item, index) => <div className="category" key={item.category}><div><span><i className={color[index]} />{item.category}</span><b>{money(item.total)}</b></div><em><i className={color[index]} style={{ width: `${total ? item.total / total * 100 : 0}%` }} /></em><small>{total ? Math.round(item.total / total * 100) : 0}% of spending</small></div>) : <Empty>Add expenses to see category data.</Empty>}</Panel><Panel className="recent"><h2>Recent transactions</h2><p>Your latest personal expenses.</p>{expenses.length ? expenses.slice(0, 5).map((item, index) => <div className="row" key={item.id}><b className={color[index % 4]}>{item.category[0]}</b><span><strong>{item.description}</strong><small>{item.category} · {formatDate(item.created_at)}</small></span><em className="bad">− {money(item.amount)}</em></div>) : <Empty>No expenses recorded.</Empty>}</Panel></div></>;
}

function Transactions({ expenses, load }) {
  const [form, setForm] = useState({ description: "", amount: "", category: "Food & Dining" }), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [showForm, setShowForm] = useState(false), [query, setQuery] = useState(""), [category, setCategory] = useState("All Categories");
  const add = async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await api("/expenses", { method: "POST", body: JSON.stringify({ ...form, amount: Number(form.amount) }) }); setForm({ description: "", amount: "", category: "Food & Dining" }); setMessage("Expense added."); load(); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const remove = async (id) => { if (!window.confirm("Delete this expense?")) return; try { await api(`/expenses/${id}`, { method: "DELETE" }); load(); } catch (e) { setMessage(e.message); } };
  const filtered = expenses.filter((x) => x.description.toLowerCase().includes(query.toLowerCase()) && (category === "All Categories" || x.category === category));
  return <><Heading title="Transactions" subtitle="Review and manage your financial activity." action={<button className="primary pale" onClick={() => setShowForm(!showForm)}>+ &nbsp; Add Transaction</button>} />{showForm && <Panel className="add-expense"><h2>Add an expense</h2><form onSubmit={add}><label>Description<input required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="e.g. Weekly groceries" /></label><label>Amount (₹)<input required min="1" step="0.01" type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} placeholder="0" /></label><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((x) => <option key={x}>{x}</option>)}</select></label><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save transaction"}</button></form>{message && <div className="notice">{message}</div>}</Panel>}<Panel className="transaction-table"><div className="transaction-tools"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="⌕  Filter by description..." /><select value={category} onChange={(e) => setCategory(e.target.value)}><option>All Categories</option>{categories.map((x) => <option key={x}>{x}</option>)}</select><button className="date-button">dd / mm / yyyy&nbsp; ▣</button><span /><button className="view-button">▤</button><button className="view-button active">▦</button></div>{filtered.length ? <table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((x) => <tr key={x.id}><td>{formatDate(x.created_at)}</td><td><b>{x.description}</b><small>{x.category}</small></td><td><span className="tag">{x.category}</span></td><td className="bad"><b>− {money(x.amount)}</b></td><td><span className="expense-status">↓ Expense</span></td><td><button className="delete" onClick={() => remove(x.id)}>Delete</button></td></tr>)}</tbody></table> : <Empty>No matching transactions.</Empty>}<div className="pagination"><span>Showing {filtered.length} of {expenses.length} entries</span><div><button disabled>Prev</button><button className="active">1</button><button disabled>Next</button></div></div></Panel></>;
}

function Analytics({ expenses, total, budget, setBudget }) {
  const [input, setInput] = useState(budget || ""), [message, setMessage] = useState(""); const grouped = groupExpenses(expenses);
  useEffect(() => setInput(budget || ""), [budget]);
  const saveBudget = async (e) => { e.preventDefault(); try { const data = await api("/budget", { method: "PUT", body: JSON.stringify({ monthly_amount: Number(input || 0) }) }); setBudget(data.monthly_amount); setMessage("Monthly budget saved."); } catch (err) { setMessage(err.message); } };
  const slice = grouped.slice(0, 4); const chartHeights = [42, 57, 48, 72, 62, 85];
  return <><Heading title="Budget & Analytics" subtitle="Track your spending and visualize your financial health." action={<div className="spending-alert"><b>⚠</b><div><strong>Spending Alert</strong><span>Your spending is {budget && total > budget ? "over budget" : "on track"} this month.</span></div></div>} /><div className="budget-metrics"><Metric label="Total budget" value={money(budget)} note="Monthly allowance" /><Metric label="Total spent" value={money(total)} note={budget ? `${Math.min(100, Math.round(total / budget * 100))}% of budget used` : "Set a monthly budget"} tone="orange" /><Metric label="Remaining" value={money(budget - total)} note={budget >= total ? "On track to save this month" : "Budget exceeded"} tone="green" /></div><div className="analytics-bento"><Panel className="category-card"><div className="panel-line"><h2>Category Budgets</h2><button>•••</button></div>{slice.length ? slice.map((item, index) => { const cap = budget ? budget / Math.max(slice.length, 1) : item.total; const pct = cap ? Math.min(100, item.total / cap * 100) : 0; return <div className="category" key={item.category}><div><span><i className={color[index]} />{item.category}</span><b>{money(item.total)} / {money(cap)}</b></div><em><i className={color[index]} style={{ width: `${pct}%` }} /></em><small className={pct >= 100 ? "bad" : ""}>{pct >= 100 ? "Over budget" : `${Math.round(pct)}% used`}</small></div>; }) : <Empty>Add expenses to see categories.</Empty>}<button className="outline-button" onClick={() => document.querySelector(".budget-input")?.focus()}>Set monthly budget</button></Panel><div className="charts"><Panel><div className="panel-line"><h2>Monthly Spending Trend</h2><span className="chart-tabs">6M&nbsp;&nbsp; <b>1Y</b></span></div><div className="bar-chart">{chartHeights.map((height, i) => <div key={i}><i style={{ height: `${height}%` }} className={i === 5 ? "current" : ""} /><span>{["Jan", "Feb", "Mar", "Apr", "May", "Jun"][i]}</span></div>)}</div></Panel><Panel className="donut-card"><div className="donut" style={{ background: slice.length ? `conic-gradient(#ff5964 0 35%,#9bbaff 35% 60%,#7f91aa 60% 75%,#2c3850 75% 100%)` : "#26344c" }}><div><small>Top Expense</small><b>{slice[0]?.category || "—"}</b></div></div><div className="donut-legend">{slice.map((item, index) => <span key={item.category}><i className={color[index]} />{item.category}<b>{total ? Math.round(item.total / total * 100) : 0}%</b></span>)}</div></Panel></div></div><Panel className="budget-save"><h2>Monthly budget</h2><p>Set the amount you plan to spend this month.</p><form onSubmit={saveBudget}><label>Budget amount (₹)<input className="budget-input" min="0" type="number" value={input} onChange={(e) => setInput(e.target.value)} placeholder="50000" /></label><button className="primary">Save budget</button></form>{message && <div className="notice">{message}</div>}</Panel></>;
}

function Insights({ total, budget }) {
  const [question, setQuestion] = useState(""), [answer, setAnswer] = useState(""), [busy, setBusy] = useState(false);
  const ask = async (e) => { e.preventDefault(); if (!question.trim()) return; setBusy(true); try { const context = `My monthly budget is ${money(budget)} and I have spent ${money(total)}. ${question}`; setAnswer((await api("/chat", { method: "POST", body: JSON.stringify({ content: context }) })).response); } catch (err) { setAnswer(err.message); } finally { setBusy(false); } };
  return <><Heading title="Your Financial Insights" subtitle="Ask for practical guidance based on your current spending." /><div className="two"><Panel className="ai"><i>✦</i><h2>Ask your AI analyst</h2><p>Get a short, useful perspective on your personal finances.</p><form onSubmit={ask}><textarea value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="How can I reduce my food spending this month?" /><button className="primary" disabled={busy}>{busy ? "Thinking…" : "Generate insight"}</button></form>{answer && <div className="answer">{answer}</div>}</Panel><Panel><h2>Try asking</h2>{["How can I stay within my budget?", "Which category should I reduce first?", "Give me a simple savings plan for this month."].map((x) => <button className="suggest" key={x} onClick={() => setQuestion(x)}>{x}<span>→</span></button>)}</Panel></div></>;
}

function Afford({ total, budget }) {
  const [name, setName] = useState("Headphones"), [price, setPrice] = useState(8000); const remaining = budget - total; const after = remaining - price; const safe = after >= 0;
  return <><Heading title="Can I Afford This?" subtitle="Check if a planned purchase fits inside your remaining monthly budget." /><div className="two"><Panel><h2>Purchase details</h2><p>Test any expense before you spend.</p><form><label>Purchase name<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Purchase price (₹)<input type="number" value={price} onChange={(e) => setPrice(Number(e.target.value))} /></label></form></Panel><Panel><div className="status"><div><small>ANALYSIS RESULT</small><h2 className={safe ? "safe" : "bad"}>{budget === 0 ? "SET A BUDGET FIRST" : safe ? "YOU CAN AFFORD THIS" : "CAUTION"}</h2></div><b>{safe ? "✓" : "!"}</b></div><div className="impact"><strong>{safe ? "Looks manageable" : "Impact warning"}</strong><p>{budget === 0 ? "Set your monthly budget in Budget & Analytics to use this tool." : safe ? `Buying ${name} still leaves ${money(after)} in your monthly budget.` : `This purchase would put you ${money(Math.abs(after))} over your monthly budget.`}</p></div><h3>Financial snapshot</h3>{[["Monthly budget", budget], ["Expenses tracked", -total], [`Purchase: ${name}`, -price]].map(([label, value]) => <div className="snap" key={label}><span>{label}</span><b className={value < 0 ? "bad" : ""}>{value < 0 ? "− " : ""}{money(Math.abs(value))}</b></div>)}<div className="project"><span>Budget left after purchase</span><b className={safe ? "safe" : "bad"}>{money(after)}</b></div></Panel></div></>;
}

function Auth({ onLogin }) {
  const [mode, setMode] = useState("login"), [username, setUsername] = useState(""), [password, setPassword] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const submit = async (e) => { e.preventDefault(); setBusy(true); setMessage(""); try { const r = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const text = await r.text(); let data = {}; try { data = text ? JSON.parse(text) : {}; } catch { data = { detail: "The server returned an invalid response." }; } if (!r.ok) throw new Error(data.detail || "Could not continue."); if (mode === "register") { setMode("login"); setMessage("Account created. Please sign in."); } else onLogin(await api("/me")); } catch (err) { setMessage(err.message); } finally { setBusy(false); } };
  const switchMode = () => { setMode(mode === "login" ? "register" : "login"); setMessage(""); };
  return <main className="auth"><Panel><div className="brand"><b>◉</b><span>FinSight</span></div><h1>{mode === "login" ? "Your spending, in focus." : "Start tracking smarter."}</h1><p>Your private personal expense tracker.</p><form onSubmit={submit}><label>Username<input required value={username} onChange={(e) => setUsername(e.target.value)} /></label><label>Password<input required minLength="8" type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button type="submit" className="primary" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button></form>{message && <div className="notice">{message}</div>}<button type="button" className="link" onClick={switchMode}>{mode === "login" ? "New here? Create an account" : "Already have an account? Sign in"}</button></Panel></main>;
}

function groupExpenses(expenses) { return Object.values(expenses.reduce((groups, item) => { const category = item.category || "Other"; groups[category] = groups[category] || { category, total: 0 }; groups[category].total += Number(item.amount); return groups; }, {})).sort((a, b) => b.total - a.total); }
function formatDate(value) { return value ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short" }) : "Today"; }
